# Site Settings
title: "Ryan Cortino's Personal Portfolio"
description: |
  A living resume and personal Portfolio for a passionate and driven
  game-systems programmer with half-a-decade of professional experience as
  a DotNet developer.
permalink: ':title/'
baseurl: ""
url: ""
site-twitter: ""

# Author Settings
author: "Ryan Cortino"
author-img: "ryan-cortino.jpg"
about-author: "Ryan is a passionate and driven .Net Developer with 5+ years experience developing backend, batch, and business intelligence solutions using DotNet, VBA, and MS SQL."
social-twitter: ""
social-facebook: ""
social-github: "RyanCortino"
social-linkedin: "ryan-cortino"
social-email: "RyanCortino@gmail.com"

# Quicklink Settings
quicklink-resume: Ryan_Cortino-Resume.pdf
quicklink-resume-title: "Ryan's Resume"
quicklink-cv: Ryan_Cortino-CV.pdf
quicklink-cv-title: "Ryan's C.V."

# Disqus
discus-identifier: #unused

# Tracker
analytics:  #unused

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
