# Site Settings
title: "Ryan Cortino's Personal Portfolio"
description: |
  A living resume and personal Portfolio for a passionate and driven
  game-systems programmer with half-a-decade of professional experience as
  a full-stack developer.
permalink: ':title/'
baseurl: ""
url: ""
site-twitter: ""

# Author Settings
author: Ryan Cortino
author-img: "ryan-cortino.png"
about-author: "I am a passionate and driven game-systems programmer with over a decade of professional experience as a Dotnet developer."
#social-twitter: ""
#social-facebook: ""
social-github: "RyanCortino"
social-linkedin: "ryan-cortino"
social-email: "RyanCortino@gmail.com"

# Disqus
discus-identifier: #unused

# Tracker
analytics:  #unused

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
