# Site settings
title: Ryan Cortino
email: RyanCortino@gmail.com
url: https://ryancortino.github.io/
description: "Passionate software engineer and hobbyist game developer with over 10 years of experience."
keywords: "Ryan Cortino, Software Engineer, Full-Stack Developer, Front-End, Database, Back-End, Game Design, Game Dev"
skills: "Web Developer | Full-Stack Software Engineer | Game-Systems Designer"
meta_author: Cortino Ryan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - comment the line below to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  brand-primary: 18bc9c #rgb(24,188,156)
  brand-primary-dark: 0E705D #rgb(14,112,93)  
  brand-primary-rgb: "24,188,156" #18bc9c
  brand-secondary: 461955 #rgb(70,25,85)
  brand-secondary-dark: 2A0F33 #rgb(42,15,51)
  brand-success: 18bc9c #rgb(24,188,156)
  brand-info: bc7f6f #rgb(188,127,111)
  brand-warning: bca918 #rgb(188,169,24)
  brand-danger: bc3918 #rgb(188,57,24)

# Footer settings
footer:
  copyright: Ryan Cortino
  location: "Dundee, Oregon"
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  linkedin-url: https://www.linkedin.com/in/ryan-cortino/
  github-url: https://github.com/RyanCortino
  stackoverflow-url: https://stackoverflow.com/users/2811385/ryan-cortino

# Postal address (add as many lines as necessary)
address: "Dundee, OR 97115"

# Build settings
markdown: kramdown
permalink: pretty
